title: Vietnam Observatory on Economics and Finance (VOEF)
description: Advancing economic and financial research by Vietnam-focused economists
baseurl: ""
theme: minima
background-image: url("{{ site.baseurl }}/assets/images/VOEF-logo-rouge.png");

header_pages:
  - index.md
  - publications.md
  - media.md
  - projects.md
